---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/forecasts/{city}":
    parameters:
    - name: city
      in: path
      description: city
      required: true
      schema:
        type: string
    get:
      summary: show forecast
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
